In [26]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
import numpy as np

dataset = fetch_california_housing()

df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
df[dataset.target_names[0]] = dataset.target

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
# inverse
E = A*B # element-wise
print(E)
print(E.T)
np.linalg.inv(E)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 24 21]
 [16 25 16]
 [21 24  9]]

array([[-0.73611111,  0.88888889, -0.65277778],
       [ 1.33333333, -1.66666667,  1.33333333],
       [-0.65277778,  0.88888889, -0.73611111]])

In [15]:
feature_1 = np.array([[123], [456], [789]])
feature_2 = np.array([[321], [654], [987]])

# Combine the two features into one matrix
print(np.hstack((feature_1, feature_2)))
print(np.vstack((feature_1, feature_2)))

[[123 321]
 [456 654]
 [789 987]]
[[123]
 [456]
 [789]
 [321]
 [654]
 [987]]

In [19]:
print(A)
A / np.linalg.norm(A) # normalize
(A - np.min(A)) / (np.max(A) - np.min(A)) # min-max normalization

[[1 2 3]
 [4 5 6]
 [7 8 9]]

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [ ]:
weights = np.array([0.2, 0.3, 0.5])
print(A, weights)
np.dot(A, weights) # weighted sum

[[1 2 3]
 [4 5 6]
 [7 8 9]] [0.2 0.3 0.5]

array([2.3, 5.3, 8.3])

In [24]:
import numpy as np
import time

# Define a large array
large_array = np.random.rand(10**6)

# Numpy way
start = time.time()
print("Numpy sum:", np.sum(large_array))  # This calculates the sum using Numpy's vectorized function
print("Time to calculate the sum in a Numpy list:", time.time() - start)
# Prints "Time to calculate the sum in a Numpy list: 0.00037097930908203125"


# Python way of summing elements in an array
start = time.time()
print("Built-in list sum", sum(large_array))  # This calculates the sum using Python's built-in function
print("Time to calculate the sum in a Python list:", time.time() - start)
# Prints "Time to calculate the sum in a Python list: 0.0417783260345459"

# Note: Timing may vary between runs due to system load, CPU throttling, and other environmental factors

Numpy sum: 500178.6463640627
Time to calculate the sum in a Numpy list: 0.0029306411743164062
Built-in list sum 500178.6463640757
Time to calculate the sum in a Python list: 0.19115662574768066

In [27]:
df['income_cat'] = pd.cut(df['MedInc'],
                               bins=[0., 1.5, 3.0, 4.5, 6., np.inf],
                               labels=["very low", "low", "medium", "high", "very high"])

In [ ]:
# The first technique is choosing the pd.Categorical data type (or use .astype('category'))
#  specifically for categorical data (data that takes on a limited, usually fixed, number of possible values), 
# which can yield significant savings in memory. Data types like integers and floats take up more memory space 
# than categorical data types, which can significantly reduce memory usage, especially for large datasets.
# Do this only with strings, if done with numerical data like days of the  week (0, 1, ..., 6) it is better to keep the numbers

df['income_cat'] = pd.Categorical(df['income_cat'])
df['income_cat'] = df['income_cat'].astype('category')

In [ ]:
# Another way is to reduce memory usage for cases where DataFrame features are not categorical. 
# In Pandas, downcast is a parameter to downcast data types of Dataframe. It's used with pd.to_numeric() 
# function to downcast data types of numeric columns to either 'integer', 'signed', 'unsigned', or 'float'.

df['AveBedrms'] = pd.to_numeric(df['AveBedrms'], downcast='float')
df['Population'] = df['Population'].astype('int32')

# Another valuable asset is method chaining, which combines several operations into one unified code line, 
# improving execution speed and enhancing code readability.

# Also, it is worth noting that the inplace parameter in Pandas operations deserves mention because it is more memory-friendly.

In [42]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [46]:
from sklearn import datasets
# Load the California Housing dataset
california = datasets.fetch_california_housing()
df = pd.DataFrame(data=np.c_[california['data'], california['target']], columns=california['feature_names'] + ['target'])

def memory_usage_pandas(df):
    bytes = df.memory_usage(deep=True).sum()
    return bytes / 1024**2  # Convert bytes to megabytes

original_memory = memory_usage_pandas(df)

# Optimize memory usage in Pandas using categorical data types
# California Housing dataset does not have any Categorical features, so we will use downcasting
df['AveBedrms'] = pd.to_numeric(df['AveBedrms'], downcast='float')
df['AveRooms'] = pd.to_numeric(df['AveRooms'], downcast='float')
df['Population'] = pd.to_numeric(df['Population'], downcast='unsigned')
df['HouseAge'] = pd.to_numeric(df['HouseAge'], downcast='unsigned')
optimized_memory = memory_usage_pandas(df)

print(f'Original memory usage: {original_memory} MB')
print(f'Optimized memory usage: {optimized_memory} MB')
print(f'Memory saved: {original_memory - optimized_memory} MB')

Original memory usage: 1.4173622131347656 MB
Optimized memory usage: 1.0040016174316406 MB
Memory saved: 0.413360595703125 MB

In [ ]:
# DNA sequences for several genes
data = {
    "Gene": ["Gene A", "Gene B", "Gene C", "Gene D"],
    "Sequence": ["ATCGTACGA", "CGATCGATG", "TAGCTAG", "CGTAGCTA"]
}

df_genes = pd.DataFrame(data)

df_genes['Length'] = df_genes['Sequence'].apply(len)
#or df_genes["Sequence"].str.len()

In [50]:
df_genes["Sequence"].str.len()

0    9
1    9
2    7
3    8
Name: Sequence, dtype: int64

In [ ]:
from sklearn import metrics

r2_score = metrics.r2_score(target_test, predictions)
print('R-squared:', r2_score) # R-squared: 0.4031803412796231

# For calculating MAE, pass the actual and predicted arrays to mean_absolute_error()
mae = metrics.mean_absolute_error(actual, fitted)
print(f"Mean Absolute Error (MAE): {mae}")
# Mean Absolute Error (MAE): 0.16666666666666666

# For calculating MSE, use the mean_squared_error function
mse = metrics.mean_squared_error(actual, fitted)

# RMSE
rmse = np.sqrt(mse)

In [ ]:
# Model Accuracy
print("Accuracy: ", metrics.accuracy_score(y_test, y_pred))
# Accuracy:  0.8875

# Model Precision
print("Precision: ", metrics.precision_score(y_test, y_pred))
# Precision:  0.5172413793103449

# Model Recall
print("Recall: ", metrics.recall_score(y_test, y_pred))
# Recall:  0.2727272727272727

# Model F1-Score
print("F1 Score: ", metrics.f1_score(y_test, y_pred))
# F1 Score:  0.3571428571428571

# Model AUC
print("AUC: ", metrics.roc_auc_score(y_test, y_pred))

# For computing AUC-ROC, we need the probabilities of the positive class ('good'), let's assume y_proba as an array of these probabilities 
y_proba = np.array([0.1, 0.7, 0.3, 0.8, 0.7])
auc_roc = metrics.roc_auc_score(y_test, y_proba)

In [ ]:
from sklearn.model_selection import cross_val_score

# clf represents an instance of a machine learning model you've already constructed (e.g., clf = LinearRegression())
scores = cross_val_score(clf, X, y, cv=5)